#' ADILSONVOL2CAP20EXEMP1
#'
#' MORTES CAUSADAS POR USO DE DROGAS
#'
#' @format A data frame with 11 rows and 2 variables:
#' \describe{
#'   \item{LOCAL}{PAIS}
#'   \item{TAXA DE MORTALIDADE}{TAXA DE MORTALIDADE A CADA UM MILHAO DE HABITANTES}
#' }
"ADILSONVOL2CAP20EXEMP1"
