#' ADILSONVOL2CAP20EXER2
#'
#' CLUBE E TORCEDORES
#'
#' @format A data frame with 7 rows and 2 variables:
#' \describe{
#'   \item{CLUBE}{CLUBE BRASILEIRO}
#'   \item{PERCENTUAL DE TORCEDORES}{TORCEDORES EM PORCENTAGEM}
#' }
"ADILSONVOL2CAP20EXER2"
