#' BALESTRIVOL2CAP7EXEM4
#'
#' NUMERACAO DO CALCADO DOS FUNCIONARIOS DE CERTA EMPRESA
#'
#' @format A data frame with 7 rows and 2 variables:
#' \describe{
#'   \item{NUMERO}{NUMERO QUE O FUNCIONARIO CALCA}
#'   \item{FREQUENCIA}{QUANTIDADE DE FUNCIONARIOS QUE CALCAM AQUELE NUMERO}
#' }
"BALESTRIVOL2CAP7EXEM4"
