#' BALESTRIVOL2CAP7EXER13
#'
#' IDADES DOS ALUNOS DO 1 ANO EM MATEMATICA EM 2016
#'
#' @format A data frame with 7 rows and 2 variables:
#' \describe{
#'   \item{IDADE}{IDADES DOS ALUNOS EM ANOS}
#'   \item{FREQUENCIA}{FREQUENCIA DOS ALUNOS COM ESSA IDADE}
#' }
"BALESTRIVOL2CAP7EXER13"
