#' BALESTRIVOL2CAP7EXER6
#'
#' DISTRIBUICAO DOS ALUNOS BRASILEIROS EM 2013
#'
#' @format A data frame with 5 rows and 3 variables:
#' \describe{
#'   \item{TIPO DE ENSINO}{TIPO DE ENSINO EM QUE OS ALUNOS ESTAO MATRICULADOS}
#'   \item{REDE PUBLICA}{ALUNOS MATRICULADOS NA REDE PUBLICA EM PORCENTAGEM}
#'   \item{REDE PARTICULAR}{ALUNOS MATRICULADOS NA REDE PARTICULAR EM PORCENTAGEM}
#' }
"BALESTRIVOL2CAP7EXER6"
