#' FABIOVOL3CAP3EXER16
#'
#' PESSOAS COM 60 ANOS OU MAIS
#'
#' @format A data frame with 7 rows and 3 variables:
#' \describe{
#'   \item{REGIOES}{REGIOES DO BRASIL}
#'   \item{2004}{VALOR DO ANO DE 2004 EM PORCENTAGEM}
#'   \item{2014}{VALOR DO ANO DE 2014 EM PORCENTAGEM}
#' }
"FABIOVOL3CAP3EXER16"
