#' FABIOVOL1CAP1EXERCOMP4
#'
#' TV POR ASSINATURA NO BRASIL
#'
#' @format A data frame with 7 rows and 2 variables:
#' \describe{
#'   \item{ANO}{ANO EM QUE FOI COLETADO OS VALORES}
#'   \item{ASSINATURA}{ASSINATURA EM MILHOES}
#' }
"FABIOVOL1CAP1EXERCOMP4"
