#' FABIOVOL1CAP1EXERCOMP4
#'
#' TV POR ASSINATURA NO BRASIL
#'
#' @format A data frame with 7 rows and 2 variables:
#' \describe{
#'   \item{ANO}{NOTAS QUE A TURMA TIROU}
#'   \item{NUMERO DE ASSINATURAS}{ASSINATURA EM MILHOES}
#' }
"FABIOVOL1CAP1EXERCOMP4"
