#' FABIOVOL3CAP3EXER22
#'
#' GASTOS COM ENERGIA ELETRICA
#'
#' @format A data frame with 51 rows and 2 variables:
#' \describe{
#'   \item{APARTAMENTO}{APARTAMENTO DO PREDIO}
#'   \item{CONSUMO}{CONSUMO DO APARTAMENTO EM KWH}
#' }
"FABIOVOL3CAP3EXER22"
