#' GELSONVOL1CAP13EXER18
#'
#' MEDALHAS DE OURO EM JOGOS OLIMPICOS
#'
#' @format A data frame with 18 rows and 2 variables:
#' \describe{
#'   \item{ANO}{ANO EM QUE ACONTECEU OS JOGOS OLIMPICOS}
#'   \item{MEDALHAS DE OURO}{QUANTIDADE DE MEDALHAS DE OURO CONQUISTADAS}
#' }
"GELSONVOL1CAP13EXER18"
